# import requests
# from requests.sessions import Session
# data={
#     "employeeEntryMSG": '{"employeeEntry":{"clickState":0,"userName":"美美","userNum":"MW00011799","userNumCopy":"MW00011799","photourl":"","checkWorkNo":"80413","firstWorkTime":"","country":"151001","idCardType":"149002","userIDCard":"963258","birthDay":"1980-06-04","isMarried":"","gender":"118002","nation":"","hukouType":"","healthEndTime":"","phone":"","weChat":"","mail":"","userType":"100010","qq":0,"urgentPerson":"","urgentPhone":"","organizeID":370,"chcekOrgID":"","postID":6169,"rankID":"235","startTime":"2019-06-19","offerTime":"","expectOfferTime":"","checkworkcode":"","bankName":"","bankCard":"","checkworkid":"68","expiryDate":"","state":"120001","origin":"","age":39,"baseSalary":0,"unit":"2","contractType":"","hireType":"","contractDateType":"","contractSignDate":"","education":"","gongling":"","subWorkYear":0,"siling":"","idCardEndTime":"","hukouAddress":"","hukouCode":0,"positionID":83,"positionName":"部门主管","political":"","showBankUrl":false,"showContractUrl":false,"showHealthUrl":false,"showIdentityUrl":false,"showRetirecontractUrl":false,"socialSecurity":"","parentSalary":"","childrenEducationSalary":"","parentBankCard":"","parentBankName":"","parentBankNameName":"","leaveType":"666","isBlack":0,"ID":""},"jobexperienceList":[],"educateList":[],"dormitory":{"ID":"","address":"","dormitoryCode":""},"extendList":[{"ID":5,"dbName":"_huodezhengshu","des":"","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":4,"dbName":"_tongjineng","des":"","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":10,"dbName":"_xianjuzhudizhi","des":"","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":14,"dbName":"_biyeyuanxiao","des":"234","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":15,"dbName":"_zhuanye","des":"234","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":16,"dbName":"_biyeshijian","des":"","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":18,"dbName":"_peiou","des":"","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":19,"dbName":"_zhaopinqudao","des":"","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":23,"dbName":"_huiyuankahao","des":"24","tableName":"employee","valid":1,"showType":"show_inputStr"},{"ID":25,"dbName":"_fangbu","des":"","tableName":"employee","valid":1,"showType":"show_radio"},{"ID":26,"dbName":"_goumaiyiwaixianriqi","des":"","tableName":"employee","valid":1,"showType":"show_date"}],"checkworkOrgList":[],"empaccessory":{"identityUrl":"","healthUrl":"","bankUrl":"","contractUrl":"","photoUrl":"","signatureUrl":"","retirecontractUrl":""},"isCommit":1,"saveOrUpdate":"S"}'
# }

# req = Session()
# req.get(url='https://dev.cxyhr.cn/login/login.htm?name=customservice&pass=a2019rlgj', verify=False)

# res = req.post(url='https://dev.cxyhr.cn/acewill/employee/addEmployeeEntry.htm', data=data, verify=False)
# print(res.text)


print(str(True))